### ISSUE TITLE
Is there a library of different boards (.IBC files)?

### ISSUE THREAD

**Issue by mishakogan** [unicorn-bi/Unicorn-Suite-Hybrid-Black#11]
I am helping my mom and looking for russian lang board?

**Comment by unicorn-bi** [comment]
hey, we don't have pre defined boards for russian language, but you can create your own unicorn speller board file. you can check the manual section "21.14. CUSTOMIZING THE BOARD AND CONFIGURING THE TIMING OF 
FLASHING"
