### ISSUE TITLE
UnicornLSL streaming only AUX channels

### ISSUE THREAD

**Issue by tomek-** [unicorn-bi/Unicorn-Suite-Hybrid-Black#7]
Hi,
I have a problem with UnicornLSL, which is streaming only AUX channels rejected by many EEG experimental environments (BCI2000, etc.). Changing a stream name in the simple UicornLSL interface has no impact. How to rename 1 to 8 channels to EEG, as it is supposed to be? 
Help! ;) 
Attached is a screenshot with BrainVision LSL viewer that can see only AUX channels but zero EEG ;(

![unicornLSLproblem](https://user-images.githubusercontent.com/7097956/152628637-23f475c1-10fd-46f5-922b-68e2ef353469.png)

**Comment by unicorn-bi** [comment]
updated lsl interface. signals can be sent in one or multiple streams now
