### ISSUE TITLE
Can I compile/Use the library in MacOS?

### ISSUE THREAD

**Issue by iPsych** [unicorn-bi/Unicorn-Suite-Hybrid-Black#8]
Can I compile/Use the library in MacOS?
If not, would you provide compiled dylib or .c file?

**Comment by unicorn-bi** [comment]
currently the api is not compiling on mac os. Currently the mac os development is cancelled.
you could use the bluetooth protocol documentation to implement it your own api to use the unicorn on mac os.
https://github.com/unicorn-bi/Unicorn-Suite-Hybrid-Black/blob/master/Unicorn%20Bluetooth%20Protocol/UnicornBluetoothProtocol.pdf
