### ISSUE TITLE
Raspberry Pi4 Example

### ISSUE THREAD

**Issue by mattin89** [unicorn-bi/Unicorn-Suite-Hybrid-Black#9]
I have a Raspberry Pi 4 running Ubuntu 18. I want to stream data to OpenVibe. I was trying to compile your example for Raspberry Pi Zero W. After running the following run in the terminal:

g++ main.cpp -I ../Lib -L ../Lib -lunicorn -o UnicornAcquisitionExample

I am getting the following error:

/usr/bin/ld: skipping incompatible ../Lib/libunicorn.so when searching for -lunicorn
/usr/bin/ld: cannot find -lunicorn
collect2: error: ld returned 1 exit status

I was wondering if the example was compatible with a Raspberry Pi 4 board. Otherwise, how do you suggest to stream data to OpenVibe using a Raspberry Pi 4?

**Comment by unicorn-bi** [comment]
We don't have a raspberry pi here so I can't test for Raspberry Pi 4. If nonre of the libraries compile you can always implement the Bluetooth API the data conversion example is avalilable in the documentation: https://github.com/unicorn-bi/Unicorn-Suite-Hybrid-Black/blob/master/Unicorn%20Bluetooth%20Protocol/UnicornBluetoothProtocol.pdf
